# Generated by Django 5.2.2 on 2025-12-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='department',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='ministry',
        ),
        migrations.AddField(
            model_name='complaint',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='complaints', to='complaints.department'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ministries',
            field=models.ManyToManyField(related_name='complaints', to='complaints.ministry'),
        ),
    ]
